apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhV05sWjJ4bGJqcG5hSEJmUlZKWFFsbDVXbTFrTjNoWFpsRkZObWRxWVRJMWEyeEhRMmwxUldkVk1GWmhabVpUIgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
